# Create the Kubernetes service account used by the connector
# and grant it read-only access to StatefulSet resources.
# This is only required when deploying the connector with
# CBES_K8S_WATCH_REPLICAS=true
apiVersion: v1
kind: ServiceAccount
metadata:
  name: couchbase-elasticsearch-connector
  namespace: default # adjust as necessary
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: couchbase-elasticsearch-conector-statefulset-reader
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: couchbase-elasticsearch-conector-read-statefulset
subjects:
  - kind: ServiceAccount
    name: couchbase-elasticsearch-connector
    namespace: default # adjust as necessary
roleRef:
  kind: ClusterRole
  name: couchbase-elasticsearch-conector-statefulset-reader
  apiGroup: rbac.authorization.k8s.io
