# Headless service to back the StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: couchbase-elasticsearch-connector-example-group
  labels:
    app: couchbase-elasticsearch-connector
    cbesGroup: example-group
spec:
  selector:
    app: couchbase-elasticsearch-connector
    cbesGroup: example-group
  clusterIP: None
  ports:
  - name: metrics
    port: 31415
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: couchbase-elasticsearch-connector-example-group
  labels:
    app: couchbase-elasticsearch-connector
    cbesGroup: example-group
spec:
  selector:
    matchLabels:
      app: couchbase-elasticsearch-connector
      cbesGroup: example-group
  serviceName: couchbase-elasticsearch-connector-example-group
  replicas: 2 # For a fixed-scale deployment, this MUST match CBES_TOTAL_MEMBERS environment variable
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: couchbase-elasticsearch-connector
        cbesGroup: example-group
    spec:
      # This custom service account is only required if you're using
      # the connector's native Kubernetes integration.
      serviceAccountName: couchbase-elasticsearch-connector
      containers:
      - image: couchbase/elasticsearch-connector:4.3.4
        name: connector
# SET RESOURCE LIMITS HERE
#        resources:
#          limits:
#            cpu: '4'
#            memory: '8Gi'
        env:
          - name: CBES_GROUP
            valueFrom:
              fieldRef:
                fieldPath: metadata.labels['cbesGroup']
          # For a simple fixed-scale deployment, set CBES_K8S_STATEFUL_SET=true
          # and set CBES_TOTAL_MEMBERS to the number of replicas in the StatefulSet.
          # Also make sure CBES_K8S_WATCH_REPLICAS is not true.
          #
          # WARNING: In this mode, YOU MUST NOT CHANGE THE REPLICA COUNT while the connector is deployed.
          #
          # NOTE: These environment variables are *Volatile API* and may change without notice.
          - name: CBES_K8S_STATEFUL_SET
            value: 'true' # true means group member number is pod ordinal + 1
          - name: CBES_TOTAL_MEMBERS
            value: '2' # must be same as spec.replicas
          # To enable native Kubernetes integration, set CBES_K8S_WATCH_REPLICAS=true
          # and use a service account that can get and watch the StatefulSet.
          # The connector will ignore CBES_K8S_STATEFUL_SET and CBES_TOTAL_MEMBERS,
          # and will instead determine group size and member number based on values
          # from the StatefulSet spec.
          #
          # NOTE: In this mode, when changing the replica count it's advisable
          #       to first scale down to zero (or delete the stateful set)
          #       before scaling back up to the desired number of replicas.
          #       Otherwise, it's theoretically possible for some pods to fail
          #       to shut down in time, which could cause stale versions of
          #       some documents to be written to Elasticsearch and remain
          #       until the documents are modified again in Couchbase.
          #
          # NOTE: This environment variable is *Volatile API* and may change without notice.
          - name: CBES_K8S_WATCH_REPLICAS
            value: 'true'
        terminationMessagePolicy: FallbackToLogsOnError
        livenessProbe:
          httpGet:
            path: /metrics
            port: 31415
          timeoutSeconds: 10
          initialDelaySeconds: 45
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 2
        volumeMounts:
        - mountPath: /opt/couchbase-elasticsearch-connector/config
          name: config
          readOnly: true
        - mountPath: /opt/couchbase-elasticsearch-connector/secrets
          name: secrets
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: elasticsearch-connector-configuration
      - name: secrets
        secret:
          secretName: elasticsearch-connector-secrets
